- hosts: localhost
  gather_facts: no
  vars:
    splunk:
      ss_file: "savedsearches.conf"
      api_host: "https://192.168.2.26:8089"
      api_ep: "servicesNS"
      app_user: "nobody"
      app: "mysearch"
      api_user: "api_user"
      api_pass: "12345678"
    s_url: "{{splunk.api_host}}/{{splunk.api_ep}}/{{splunk.app_user}}"
    s_app: "apps/{{ splunk.app }}"
  tasks:
    # - name: "print filename"
    #   debug:
    #     msg: "apps/{{ splunk.app }}/{{ splunk.ss_file }}"
    -name: "Get config files per app"
      set_fact: 
        s_app_configs: "{{ s_app_configs|default([]) + [ item.key ] }}"
      with_fileglob:
        - "{{s_app}}/local/*.conf"

    - name: "Execute splunkConfParser"
      script: /usr/bin/python lib/splunkConfParser.py  "apps/{{ splunk.app }}/{{ s_app_configs }}"
      register: splunkConfParser_output
      
    - name: "set variables for json keys"
      set_fact:
        splunkConfParser_json_keys: "{{ splunkConfParser_json_keys|default([]) + [ item.key ] }}"
      with_dict:
        - "{{ splunkConfParser_output.stdout }}"
      no_log: true

    # - name: "print contents"
    #   debug:
    #     msg: "{{item}}"
    #   loop:
    #     - "{{ splunkConfParser_output }}" 
    - name: "List  Apps"
      uri:
        url: "{{splunk.api_host}}/services/apps/local"
        user: "{{splunk.api_user}}"
        password: "{{splunk.api_pass}}"
        validate_certs: false
        method: POST
        body: 
          - [ name, "{{item}}" ]
        body_format: form-urlencoded
        force_basic_auth: yes
        status_code: [200, 201,400,404,409]
        return_content: yes
      loop:
        - "{{ splunk.app }}"

    # - meta: end_play

    - name: "Deploy Config - DELETE"
      uri:
        url: "{{s_url}}/{{splunk.app}}/configs/conf-savedsearches/{{item}}"
        user: "{{splunk.api_user}}"
        password: "{{splunk.api_pass}}"
        validate_certs: false
        method: DELETE
        force_basic_auth: yes
        status_code: [200, 201,400,404,409]
      with_items:
        - "{{ splunkConfParser_json_keys }}"

    - name: "Deploy Config - POST"
      uri:
        url: "{{s_url}}/{{splunk.app}}/configs/conf-savedsearches"
        user: "{{splunk.api_user}}"
        password: "{{splunk.api_pass}}"
        validate_certs: false
        method: POST
        body: 
          - [ name, "{{item}}" ]
        body_format: form-urlencoded
        force_basic_auth: yes
        status_code: [200, 201,409]
      with_items:
        - "{{ splunkConfParser_json_keys }}"

    - name: "Deploy Config - details"
      uri:
        url: "{{s_url}}/{{splunk.app}}/configs/conf-savedsearches/{{item.key}}"
        user: "{{splunk.api_user}}"
        password: "{{splunk.api_pass}}"
        validate_certs: false
        method: POST
        body: "{{item.value}}"
        body_format: form-urlencoded
        force_basic_auth: yes
        status_code: [200,201]
      with_dict:
        - "{{ splunkConfParser_output.stdout }}"
