- hosts: localhost
  gather_facts: no
  vars:
    splunk:
      ss_file: "sampleSavedSearch.conf"
  tasks:
    - name: "print filename"
      debug:
        msg: "{{ splunk.ss_file }}"
    - name: "Execute splunkConfParser"
      script: /usr/bin/python lib/splunkConfParser.py {{ splunk.ss_file }}
      register: splunkConfParser_output
    - name: "print contents"
      debug:
        msg: "{{ splunkConfParser_output.stdout_lines }}"    
    